const mongoose = require("mongoose");

const FranchiseSelfServiceSchema = new mongoose.Schema({
  franchiseId: { type: String, required: true, unique: true },
  franchiseOwner: { type: String, required: true }, // Franchise Owner Name
  contactInfo: {
    email: { type: String, required: true },
    phone: { type: String, required: true },
  },
  totalRevenue: { type: Number, default: 0 }, // Total revenue generated by the franchise
  totalSales: { type: Number, default: 0 }, // Total sales done by franchise
  commissionEarned: { type: Number, default: 0 }, // AI-based calculated commission
  payoutsReceived: { type: Number, default: 0 }, // Total payouts received
  activeVendors: { type: Number, default: 0 }, // Vendors managed by the franchise
  activeCustomers: { type: Number, default: 0 }, // Customers associated with the franchise
  salesTrend: {
    daily: { type: Number, default: 0 },
    weekly: { type: Number, default: 0 },
    monthly: { type: Number, default: 0 },
    yearly: { type: Number, default: 0 },
  },
  aiRevenueForecast: { type: Number, default: 0 }, // AI-based prediction of future earnings
  lastPayoutDate: { type: Date, default: null }, // Last date of payout received
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const FranchiseSelfService = mongoose.model("FranchiseSelfService", FranchiseSelfServiceSchema);
module.exports = FranchiseSelfService;
